### ISSUE TITLE
Possible improvements to steps description

### ISSUE THREAD

**Issue by sozos** [melvinzhang/contrib-test#3]
1) Mention "cd" to cloned directory before creating new file
2) Step 5: "origin HEAD:master" is unnecessary? "git push" should be sufficient"
3) Step 7: "green" instead of "greeen"
4) Step 9: Instead of "git pull --rebase", should pull the upstream, then push to own branch.

**Comment by melvinzhang** [comment]
Please send a pull request. Thanks.
